### ISSUE TITLE
Doesn't work for me on Fedora 39

### ISSUE THREAD

**Issue by mak448a** [alegrey91/thinkpad-led#1]
So I run ./thinkpad-led on, and it gives me this error:
```
2023/11/10 11:26:21 File /sys/kernel/debug/ec/ec0/io does not exist. Try to load kernel module: sudo modprobe ec_sys write_support=1
```

So I run `sudo modprobe ec_sys write_support=1` like it tells me too, but  then it says `modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.5.11-300.fc39.x86_64`. Do you know how to fix this? Thank you

**Comment by alegrey91** [comment]
Hi @mak448a , thanks for opening this issue.
Unfortunately, as far as I remember, the `ec_sys`  module is no longer included in the recent kernel versions.
This utility worked until fedora 34 I think 😔
